### ISSUE TITLE
创建Charge对象时 报OpenSSL的错误 

### ISSUE THREAD

**Issue by TedYin** [PingPlusPlus/pingpp-ruby#3]
OpenSSL::SSL::SSLError: SSL_connect returned=1 errno=0 state=SSLv3 read server certificate B: certificate verify failed

服务端Ruby: 2.3.0
openssl gem : 0.2.0
openssl : openssl-1.0.1e

**Comment by samurai00** [comment]
这个应该是 ca 证书不对。你 openssl 的 cacert 是不是坏了，试一下这个 https://gist.github.com/mislav/5026283

或者试一下把这个证书更新一下 https://github.com/PingPlusPlus/pingpp-ruby/blob/master/lib/data/ca-certificates.crt

**Comment by TedYin** [comment]
@samurai00 我的CA用的就是 Ping++ gem 里面的证书。

**Comment by qiao2818** [comment]
今天出现了同样的问题

**Comment by samurai00** [comment]
@qiao2818 这个不是 SDK 的问题。改一下服务器的 hosts 文件，绑定 `api.pingxx.com` 到 `121.43.74.100` 这个 IP。先这么改。建议你升级 ruby。

**Comment by wlchn** [comment]
按照samurai00绑定ip的方法，已解决。ruby-2.2.1
