### ISSUE TITLE
ping++ 不兼容rails 5.0

### ISSUE THREAD

**Issue by dskyu** [PingPlusPlus/pingpp-ruby#4]
报错信息
Resolving dependencies...
Bundler could not find compatible versions for gem "mime-types":
  In snapshot (Gemfile.lock):
    mime-types (= 3.1)

  In Gemfile:
    rails (< 5.1, >= 5.0.0.rc1) was resolved to 5.0.0.rc1, which depends on
      actionmailer (= 5.0.0.rc1) was resolved to 5.0.0.rc1, which depends on
        mail (>= 2.5.4, ~> 2.5) was resolved to 2.6.4, which depends on
          mime-types (< 4, >= 1.16)

```
pingpp was resolved to 1.0.2, which depends on
  mime-types (< 3.0, >= 1.25)
```

Running `bundle update` will rebuild your snapshot from scratch, using only
the gems in your Gemfile, which may resolve the conflict.

**Comment by GiaoGiaoCat** [comment]
https://github.com/PingPlusPlus/pingpp-ruby/pull/7
我提交了一个PR，支持到最新的 Rails 5.0.0，等待合并呢

**Comment by samurai00** [comment]
#7 已合并。但做了修改。
