### ISSUE TITLE
Pingpp::Webhook.verify? 支持将pub_key作为参数传入

### ISSUE THREAD

**Issue by warmwind** [PingPlusPlus/pingpp-ruby#9]
当系统内有多个pingpp的账户时，pub_key就不是全局唯一的了，所以目前的方式无法针对这样的场景来使用。
另外，pub_key作为参数的话可以将这个方法完全独立为一个工具方法，对外部就没有依赖了。
如果pub_key传入为空的时候，可以默认使用Pingpp.pub_key

**Comment by warmwind** [comment]
提了一pr #10

**Comment by samurai00** [comment]
已合并

**Comment by warmwind** [comment]
可否更新下gem版本？
